apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobless-front-deployment
  labels:
    app: jobless-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobless-front
  template:
    metadata:
      labels:
        app: jobless-front
    spec:
      containers:
      - name: jobless-front
        image: arthurleroudier/jobless_front:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
        env:
                - name: FRONT_KEY
                  valueFrom:
                    secretKeyRef:
                      name: front-jeton
                      key: FRONT_KEY