apiVersion: v1
kind: Service
metadata:
  name: jobless-front-service
spec:
  type: LoadBalancer
  selector:
    app: jobless-front
  ports:
    - name: jobless-front-port
      protocol: TCP
      port: 8
      targetPort: 8501
