apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobless-deployment
  labels:
    app: jobless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobless
  template:
    metadata:
      labels:
        app: jobless
    spec:
      containers:
      - name: jobless
        image: arthurleroudier/jobless:latest
        ports:
        - containerPort: 8000
        env:
                - name: API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: api-jeton
                      key: API_KEY
