apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobless-deployment
  labels:
    app: jobless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobless
  template:
    metadata:
      labels:
        app: jobless
    spec:
      containers:
      - name: titanic
        image: arthurleroudier/jobless:latest
        ports:
        - containerPort: 4000
